services:
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_book
    volumes:
      - book_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  book_data:

