name: book workflow
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature
jobs:
  unit-testing:
    container:
      image: maven:3.9.3-eclipse-temurin-17
    services:
      postgres-db:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{vars.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{vars.POSTGRES_DB}}
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${{vars.POSTGRES_DB}}
      SPRING_DATASOURCE_USERNAME: ${{vars.POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Build and Test
        run: mvn clean test
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: test-coverage
        run: echo test-coverage
  docker-containerization:
    runs-on: ubuntu-latest
    steps:
      - name: docker
        run: echo docker the app
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: kubernetes deploy
        run: echo deploy on kubernetes